# Generated by Django 2.2 on 2019-05-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasilore',
            old_name='hasilore',
            new_name='hasil',
        ),
    ]
