# Generated by Django 2.2 on 2019-05-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0003_remove_hasilore_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilore',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
