# Generated by Django 2.2 on 2019-05-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0004_hasilore_keterangan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilore',
            name='keterangan',
        ),
    ]
