# Generated by Django 2.2 on 2019-05-27 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produksi', '0006_hasilore_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilore',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hasilore',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
