# Generated by Django 2.2 on 2019-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiltangki',
            name='nama',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tangkiinduk',
            name='nama',
            field=models.CharField(max_length=20),
        ),
    ]
