# Generated by Django 2.2 on 2019-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0003_transaksimobiltangki_transaksitangkiinduk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiltangki',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='tangkiinduk',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaksimobiltangki',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaksitangkiinduk',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
