# Generated by Django 2.2 on 2019-06-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0005_auto_20190527_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobiltangki',
            options={'ordering': ['nama'], 'verbose_name': 'Daftar Mobil Tangki', 'verbose_name_plural': 'Daftar Mobil Tangki'},
        ),
        migrations.AlterModelOptions(
            name='tangkiinduk',
            options={'ordering': ['nama'], 'verbose_name': 'Daftar Tangki Induk', 'verbose_name_plural': 'Daftar Tangki Induk'},
        ),
        migrations.AlterField(
            model_name='transaksitangkiinduk',
            name='mobilid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bbm.Mobiltangki'),
        ),
    ]
