# Generated by Django 2.2 on 2019-06-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0006_auto_20190606_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksitangkiinduk',
            name='mobilid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbm.Mobiltangki'),
        ),
    ]
