# Generated by Django 2.2 on 2019-06-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0008_auto_20190606_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksimobiltangki',
            name='masuk',
        ),
        migrations.RemoveField(
            model_name='transaksimobiltangki',
            name='tangkiid',
        ),
        migrations.AlterField(
            model_name='transaksitangkiinduk',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
