# Generated by Django 2.2 on 2019-06-07 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kendaraanlain', '0001_initial'),
        ('alatberat', '0021_auto_20190606_1321'),
        ('bbm', '0009_auto_20190607_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksimobiltangki',
            name='alatid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alatberat.Alatberat'),
        ),
        migrations.AddField(
            model_name='transaksimobiltangki',
            name='kendaraanid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kendaraanlain.Kendaraanlain'),
        ),
    ]
