# Generated by Django 2.2 on 2019-06-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0010_auto_20190607_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksimobiltangki',
            name='alatid',
            field=models.ForeignKey(blank=True, help_text='Alat berat yg menggunakan BBM', null=True, on_delete=django.db.models.deletion.CASCADE, to='alatberat.Alatberat'),
        ),
        migrations.AlterField(
            model_name='transaksimobiltangki',
            name='kendaraanid',
            field=models.ForeignKey(blank=True, help_text='Kendaraan / alat lain pengguna BBM', null=True, on_delete=django.db.models.deletion.CASCADE, to='kendaraanlain.Kendaraanlain'),
        ),
    ]
