# Generated by Django 2.0 on 2019-06-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0012_transaksitangkiinduk_sisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksitangkiinduk',
            name='sisa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
