# Generated by Django 2.0 on 2019-06-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbm', '0014_remove_transaksitangkiinduk_sisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=100)),
                ('telp', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='transaksitangkiinduk',
            name='agentid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bbm.Agent'),
            preserve_default=False,
        ),
    ]
