# Generated by Django 2.2 on 2019-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namasupplier', models.TextField(db_index=True, max_length=30)),
                ('alamat', models.TextField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kota', models.TextField(blank=True, db_index=True, max_length=20)),
                ('kontak', models.TextField(blank=True, max_length=20)),
                ('kontakhp', models.TextField(blank=True, max_length=15)),
                ('teknisi', models.TextField(blank=True, max_length=20)),
                ('teknisihp', models.TextField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
            },
        ),
    ]
