# Generated by Django 2.2 on 2019-05-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alatberat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaalat', models.TextField(max_length=30)),
                ('hargasewa', models.DecimalField(decimal_places=2, max_digits=15)),
                ('perhitungansewa', models.TextField(max_length=10)),
                ('keterangan', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.Supplier')),
            ],
            options={
                'verbose_name': 'Daftar Alat Berat',
                'verbose_name_plural': 'Daftar Alat Berat',
            },
        ),
    ]
