# Generated by Django 2.2 on 2019-05-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operatorab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaoperator', models.TextField(max_length=30)),
                ('alamat', models.TextField(blank=True, max_length=30)),
                ('hp', models.TextField(blank=True, max_length=15)),
                ('foto', models.ImageField(blank=True, upload_to='foto/')),
                ('gajipokok', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tunjangan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('catatan', models.TextField()),
            ],
            options={
                'verbose_name': 'Operator Alat Berat',
                'verbose_name_plural': 'Operator Alat Berat',
            },
        ),
        migrations.AlterModelOptions(
            name='alatberat',
            options={'ordering': ['namaalat'], 'verbose_name': 'Daftar Alat Berat', 'verbose_name_plural': 'Daftar Alat Berat'},
        ),
        migrations.RenameField(
            model_name='alatberat',
            old_name='perhitungansewa',
            new_name='jenissewa',
        ),
        migrations.CreateModel(
            name='Hourmeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('starthm', models.DecimalField(decimal_places=2, max_digits=15)),
                ('endhm', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alatberat.Alatberat')),
                ('operatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alatberat.Operatorab')),
            ],
        ),
    ]
