# Generated by Django 2.2 on 2019-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0003_auto_20190521_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourmeter',
            name='tanggal',
            field=models.DateField(db_index=True),
        ),
    ]
