# Generated by Django 2.2 on 2019-05-21 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0004_auto_20190521_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourmeter',
            old_name='endhm',
            new_name='hmakhir',
        ),
        migrations.RenameField(
            model_name='hourmeter',
            old_name='starthm',
            new_name='hmawal',
        ),
        migrations.AddField(
            model_name='hourmeter',
            name='hmdunia',
            field=models.DecimalField(decimal_places=0, default=9, max_digits=10),
        ),
        migrations.AddField(
            model_name='hourmeter',
            name='ot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hourmeter',
            name='shift',
            field=models.CharField(choices=[('SIANG', 'SIANG'), ('MALAM', 'MALAM')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biayaab',
            name='tanggal',
            field=models.DateField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='hourmeter',
            name='tanggal',
            field=models.DateField(db_index=True, default=datetime.datetime.now),
        ),
    ]
