# Generated by Django 2.2 on 2019-05-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0005_auto_20190521_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourmeter',
            name='ot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
