# Generated by Django 2.2 on 2019-05-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0006_auto_20190521_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourmeter',
            name='keterangan',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
