# Generated by Django 2.2 on 2019-05-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0008_auto_20190521_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alatberat',
            name='jenissewa',
            field=models.CharField(choices=[('JAM', 'JAM'), ('BULAN', 'BULAN')], max_length=10),
        ),
    ]
