# Generated by Django 2.2 on 2019-05-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0009_auto_20190521_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatorab',
            old_name='uanghadir',
            new_name='hadirmalam',
        ),
        migrations.AddField(
            model_name='operatorab',
            name='hadirpagi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
