# Generated by Django 2.2 on 2019-05-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0011_auto_20190521_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='alatberat',
            name='bbmperjam',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
