# Generated by Django 2.2 on 2019-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0012_alatberat_bbmperjam'),
    ]

    operations = [
        migrations.AddField(
            model_name='alatberat',
            name='jadwalhmservice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
