# Generated by Django 2.2 on 2019-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0013_alatberat_jadwalhmservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alatberat',
            name='namaalat',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='biayaab',
            name='keterangan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operatorab',
            name='alamat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='operatorab',
            name='hp',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='operatorab',
            name='namaoperator',
            field=models.CharField(max_length=30),
        ),
    ]
