# Generated by Django 2.2 on 2019-05-27 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0014_auto_20190522_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hasilore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True, default=datetime.datetime.now)),
                ('hasilore', models.DecimalField(decimal_places=2, max_digits=15)),
                ('alatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alatberat.Alatberat')),
            ],
            options={
                'verbose_name': 'Hasil Ore',
                'verbose_name_plural': 'Hasil Ore',
                'ordering': ['tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Bbmab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True, default=datetime.datetime.now)),
                ('hmnow', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hmbefore', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ltrmasuk', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.CharField(max_length=50)),
                ('alatid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alatberat.Alatberat')),
            ],
            options={
                'verbose_name': 'Input Pengisian BBM',
                'verbose_name_plural': 'Input Pengisian BBM',
                'ordering': ['tanggal'],
            },
        ),
    ]
