# Generated by Django 2.2 on 2019-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0016_auto_20190527_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alatberat',
            name='keterangan',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='bbmab',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='biayaab',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hasilore',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hourmeter',
            name='keterangan',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='operatorab',
            name='catatan',
            field=models.TextField(blank=True, default=None),
        ),
    ]
