# Generated by Django 2.2 on 2019-05-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0017_auto_20190527_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hasilore',
        ),
    ]
