# Generated by Django 2.2 on 2019-05-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0018_delete_hasilore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbmab',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Input Pengisian BBM Alat', 'verbose_name_plural': 'Input Pengisian BBM Alat'},
        ),
        migrations.AlterModelOptions(
            name='biayaab',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Biaya / Service', 'verbose_name_plural': 'Biaya / Service'},
        ),
    ]
