# Generated by Django 2.2.3 on 2019-09-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0021_auto_20190606_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='biayaab',
            name='kerusakan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='biayaab',
            name='sparepart',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='biayaab',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
    ]
