# Generated by Django 2.2.3 on 2019-10-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alatberat', '0022_auto_20190911_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorab',
            name='mingguraya',
        ),
        migrations.AddField(
            model_name='alatberat',
            name='mingguraya',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='biayaab',
            name='kerusakan',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='biayaab',
            name='keterangan',
            field=models.TextField(blank=True, default=None),
        ),
    ]
